### ISSUE TITLE
PP management with engine

### ISSUE THREAD

**Issue by mingu600** [pmariglia/foul-play#76]
Hello! I have been using your showdown engine and it's really cool. I just had a quick question- is PP management implemented? It looks like PP management isn't an "instruction" from giving a move, and also "Side" methods like get_self_options don't check if a move is out of PP, but rather if a move is disabled. Do I need to manually reduce a move's PP count by changing it in mutator.state, and then disable the move if the PP is 0, or is that functionality already there somewhere with the engine? Thanks!

**Comment by pmariglia** [comment]
PP management is not implemented. The instructions generated from using a move do not include any kind of _decrement_pp_ instruction. Doing so is possible, but it would provide little benefit for a bot that can only see 2 turns ahead.

If the bot is out of PP then the PokemonShowdown server will tell it that it's move is disabled, so there's no worry about getting stuck because it is trying to use a move that is out of PP.

**Comment by pmariglia** [comment]
Also related to this:

The PokemonShowdown server does not send specific move information for your reserve Pokemon. This means that if the bot has a reserve Pokemon with a move that is out of PP then it will think that it can switch-in and use that move, when in reality it cannot. This can probably have some performance implications.
